### ISSUE TITLE
Update default config for nerd fonts v3

### ISSUE THREAD

**Issue by allie-wake-up** [TheKiteEatingTree/swaycons#3]
A lot of the default icons do not work with the latest release of nerd fonts

![image](https://user-images.githubusercontent.com/1377778/236523704-e5d9094e-d04d-4127-96b8-409a819ea473.png)

**Comment by allie-wake-up** [comment]
Can possibly just use this: https://gist.github.com/mischw/78e8e42c2ebb1069560a2fc4573b1425

**Comment by elken** [comment]
Can confirm that script seems to work fine

**Comment by allie-wake-up** [comment]
Yea, it worked great.  Just released a new version with the updates
