### ISSUE TITLE
Update Cargo.lock

### ISSUE THREAD

**Issue by boomshroom** [TheKiteEatingTree/swaycons#6]
```
error: the lock file /build/source/Cargo.lock needs to be updated but --frozen was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --frozen flag and use --offline instead.
```

It seems Rust requires the Cargo.lock file be kept up to date with Cargo.toml even if none of the dependencies changed. When packaging, it's important that the packages and dependencies be deterministic, hence why freezing Cargo.lock can be important.

**Comment by allie-wake-up** [comment]
just updated it, let me know if there are any other issues with it
