### ISSUE TITLE
Unable to render span tag in titlebar with Sway WM

### ISSUE THREAD

**Issue by steveljko** [TheKiteEatingTree/swaycons#7]
I'm using Sway WM and I have tried everything, but I cannot manage to render the span tag in the title bar. Has anyone encountered this issue and how did you resolve it?

Here is picture:

![bbbbbbbb](https://github.com/user-attachments/assets/f6239fa7-e43b-46ae-a40a-b7d977787ae0)

**Comment by allie-wake-up** [comment]
What does your sway font config look like, is it possible that pango isn't enabled? For example this is how mine is configured `font pango:FiraCode Nerd Font 11`.

**Comment by steveljko** [comment]
You're right, pango wasn't enabled. Thanks!
